name: Coupon Publisher

on:
  schedule:
    - cron: '0 8 * * *'  # 8AM UTC = 9AM توقيت الجزائر
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: pip install -r requirements.txt
          
      - name: Run Bot
        env:
          GCP_CREDS: ${{ secrets.GCP_CREDS }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
        run: python coupon_bot.py
