name: Coupon Publisher

on:
  schedule:
    - cron: '0 9 * * *'  # 9AM UTC
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Debug Sheet Connection
        run: |
          python -c "import gspread; from oauth2client.service_account import ServiceAccountCredentials; import json; import os; \
          creds = json.loads(os.getenv('GCP_CREDS')); \
          scope = ['https://www.googleapis.com/auth/spreadsheets', 'https://www.googleapis.com/auth/drive.metadata.readonly']; \
          credentials = ServiceAccountCredentials.from_json_keyfile_dict(creds, scope); \
          client = gspread.authorize(credentials); \
          print('الحساب المرتبط:', credentials.service_account_email); \
          print('الملفات المتاحة:', client.list_spreadsheet_files())"
        env:
          GCP_CREDS: ${{ secrets.GCP_CREDS }}
          
      - name: Run Bot
        env:
          GCP_CREDS: ${{ secrets.GCP_CREDS }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
        run: python coupon_bot.py
